#
# Voltus Scheduler command file generated by voltus_rail on Fri May 15 23:21:35 2026
#
setvar log_file ./work/voltus_extractor.log
extracted_nets VSS VDD 
setvar output_cache_directory_name /tmp/ssv_tmpdir_2291767_pdhEcI/zx_tmp_TC-DL5_2292161
setvar library_name /home/wei0829/voltus_tdt_question_ng45_gcd/inputs/pgv/techonly.cl
setvar output_directory_name ./work
setvar output_file_name TopLevelPGDB
setvar output_multi_pgdb true
setvar max_error_messages 100
setvar max_resistor_length 800
setvar hierarchy_char /
layout_file /home/wei0829/voltus_tdt_question_ng45_gcd/inputs/design/6_final.def  
setvar exec_token "/home/wei0829/voltus_tdt_question_ng45_gcd/inputs/design/6_final.def"
setvar enable_signal_via_overhang false
setvar extraction_mode signoff
setvar zx_multinet_extraction true
extraction_type all none
extraction_type pattern VSS decoupled_rc
hierarchical_path_tracer netinst_table ./work/VSS.netinst
hierarchical_path_tracer cell_table ./work/VSS.cellinst
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
extraction_type pattern VDD decoupled_rc
hierarchical_path_tracer netinst_table ./work/VDD.netinst
hierarchical_path_tracer cell_table ./work/VDD.cellinst
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
hierarchical_path_tracer pgnet_table ./work/all.pgnets
setvar output_def false
setvar cluster_via_size 25
setvar cluster_via1_maximum true
setvar def_merge_supply_shorts false
setvar promote_ports true
setvar max_cpu 8
setvar create_seg_length_resistors true
setvar density_check_method database
setvar sfedb_path ./work/SFEDB 
setvar enable_binary_inst_pgdb true
setvar keep_log_file false
setvar switch_trace true
